name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
env:
  stdout: true
  stderr: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        id: out        
        run: |
         echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
         echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"

      - name: Print
        id: print
        run: |
          echo ${{ fromjson(steps.out.outputs) }}
