name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
env:
  stdout: true
  stderr: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Script
        id: script
        run: |
          script gh_output.txt
          
      - name: Output
        id: out        
        run: |
         echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
         echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"

      - name: Exit Script
        id: ext
        run: |
          ls -lr
          exit

      - name: Print
        id: print
        run: |
          cat gh_output.txt

      - name: Check
        id: check
        run: |
         grep -w "Missing semicolon" gh_output.txt
